server:
  port: 0

spring:
  jwt:
    secretKey: zbfpel
  application:
    name: user-service
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: curady13@gmail.com
    password: edeatrfqpzxynitf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  social:
    kakao:
      client_id:
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  sql:
    init:
      data-locations: classpath*:initdata/curady_user/data.sql
      mode: always

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true

springdoc:
  packagesToScan: com.curady.userservice

---

spring:
  config:
    activate:
      on-profile: local
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://localhost:3306/curady_user
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  social:
    kakao:
      redirect: http://localhost:8000/user-service/login/kakao

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mariadb://curady-user-db.cd3lqz4oykix.ap-northeast-2.rds.amazonaws.com:3306/curady_user
    driver-class-name: org.mariadb.jdbc.Driver
    username: roman
    password: ro-man-0509
  social:
    kakao:
      redirect: http://13.124.70.83:8000/user-service/login/kakao

eureka:
  client:
    service-url:
      defaultZone: http://10.0.140.187:8761/eureka
