server:
  port: 0

spring:
  jwt:
    secretKey: zbfpel
  application:
    name: user-service
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: curady13@gmail.com
    password: edeatrfqpzxynitf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  social:
    kakao:
      client_id: 254b82e58533145de909f613785d9999
      redirect: http://curady.kr/auth/kakao/callback
      url:
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me

    google:
      client_id: 820009626444-fpmpr75ik4d3409e98h3tvj7dhu713ia.apps.googleusercontent.com
      client_secret: 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
      redirect: http://curady.kr/auth/google/callback
      url:
        token: https://oauth2.googleapis.com/token
        profile: https://www.googleapis.com/oauth2/v3/userinfo

    naver:
      client_id: D2BLS_XOE7YKWdj7n7VG
      client_secret: RTOiCrsXLN
      redirect: http://curady.kr/auth/naver/callback
      url:
        token: https://nid.naver.com/oauth2.0/token
        profile: https://openapi.naver.com/v1/nid/me
  sql:
    init:
      data-locations: classpath*:initdata/curady_user/data.sql
      mode: always

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true

springdoc:
  packagesToScan: com.curady.userservice

---

spring:
  config:
    activate:
      on-profile: local
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://localhost:3306/curady_user
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mariadb://curady-user-db.cd3lqz4oykix.ap-northeast-2.rds.amazonaws.com:3306/curady_user
    driver-class-name: org.mariadb.jdbc.Driver
    username: roman
    password: ro-man-0509

eureka:
  client:
    service-url:
      defaultZone: http://10.0.140.187:8761/eureka
